name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly: Sundays 00:00 UTC (free-tier friendly)
  workflow_dispatch:  # Manual trigger

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      # Step 1: Total Time + Core Sections (Languages, Editors, Projects)
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # Core: Total-Focused Balance
          SHOW_TOTAL_CODE_TIME: 'true'      # Total hours (e.g., "1,234 hrs")
          SHOW_LANGUAGE: 'true'             # All-time top langs
          SHOW_EDITORS: 'true'              # Editor prefs
          SHOW_PROJECTS: 'true'             # Top projects by time
          
          # Exclusions: Positive Only
          SHOW_LINES_OF_CODE: 'false'       # No quantity
          SHOW_COMMIT: 'false'              # No patterns
          SHOW_OS: 'false'                  # Skipped
          SHOW_PROFILE_VIEWS: 'true'        # Engagement
          SHOW_UPDATED_DATE: 'true'         # Freshness
          UPDATED_DATE_FORMAT: "%Y-%m-%d"   # Clean date
          
          # Visuals: Dark-Friendly
          SYMBOL_VERSION: '2'               # Filled bars (blue-adapted in dark)
          LOCALE: 'en'
          
          # Commit
          COMMIT_BY_ME: 'false'             # Bot
          COMMIT_MESSAGE: 'chore: update total stats'
          SECTION_NAME: 'waka'              # Matches first markers

      # Step 2: Weekly Time Block (Total This Week + Top 3 Langs)
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # Weekly Config: Brief & Momentum-Focused
          SHOW_TITLE: 'true'                # Header: "This Week"
          TIME_RANGE: 'last_7_days'         # Weekly total
          LANG_COUNT: 3                     # Top 3 (no clutter)
          SHOW_TIME: 'true'                 # Time per lang
          SHOW_TOTAL: 'true'                # Weekly total hours
          BLOCKS: '-▮▮▮▮▮▮▮▮▮▮▯▯▯▯▯▯▯▯▯▯'  # Custom bar for dark pop (adjust if needed)
          
          # Polish
          SECTION_NAME: 'waka-weekly'       # Matches second markers
          COMMIT_MESSAGE: 'chore: update weekly stats'
          COMMIT_BY_ME: 'false'             # Bot
